FROM jupyterhub/jupyterhub:3.1.0

RUN apt update && \
    apt install -y \
        patch \
        g++ \
        python3-dev \
        --

RUN python3 -m pip install \
    dockerspawner \
    opensarlab-backend==1.0.4 \
    netifaces \
    --

COPY jupyterhub_config.py /etc/jupyterhub/jupyterhub_config.py

RUN mkdir -p /usr/local/lib/osl
COPY portal_auth.py /usr/local/lib/osl/portal_auth.py

ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/osl

RUN mkdir -p -m 775 /usr/local/secrets && chown 1000:root /usr/local/secrets
